services:
  postgres:
    image: postgres:17
    container_name: ql_postgres
    environment:
      POSTGRES_USER: ql_user
      POSTGRES_PASSWORD: ql_pass
      POSTGRES_DB: ql_demo
    ports:
      - "5432:5432"
    command: >
      postgres
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.track=all
        -c pg_stat_statements.max=10000
        -c track_activity_query_size=4096
        -c log_lock_waits=on
        -c deadlock_timeout=1s
        -c shared_buffers=16MB
        -c logging_collector=on
        -c log_destination=csvlog
        -c log_directory=/pg_logs
        -c log_filename=postgresql.log
        -c log_min_duration_statement=0
    volumes:
      - ./init/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
      - postgres_data:/var/lib/postgresql/data
      - ./pg_logs:/pg_logs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ql_user -d ql_demo"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ql_network

  mysql:
    image: mysql:8.0
    container_name: ql_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ql_root
      MYSQL_DATABASE: ql_demo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3307:3306"
    command: >
      --performance-schema=ON
      --performance-schema-instrument='statement/%=ON'
      --performance-schema-consumer-events-statements-history=ON
      --performance-schema-consumer-events-statements-history-long=ON
      --performance-schema-consumer-events-waits-current=ON
      --max_connections=1000
      --performance-schema-consumer-statements-digest=ON
      --performance-schema-consumer-events-waits-current=ON
      --performance-schema-consumer-events-waits-history=ON
      --performance-schema-instrument='wait/io/table/sql/handler=ON'
      --temptable_max_ram=1048576
      --slow-query-log=ON
      --slow-query-log-file=/mysql_logs/ql-slow.log
      --long-query-time=0
      --log-output=FILE
    volumes:
      - ./init/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
      - mysql_data:/var/lib/mysql
      - ./mysql_logs:/mysql_logs
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pql_root"]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - ql_network

  sysbench:
    image: debian:bookworm-slim
    container_name: ql_sysbench
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y --no-install-recommends sysbench default-mysql-client postgresql-client &&
        tail -f /dev/null
      "
    networks:
      - ql_network

volumes:
  postgres_data:
  mysql_data:

networks:
  ql_network:
    driver: bridge